name: climatoology
channels:
  - conda-forge
dependencies:
  - pip=23.2
  - python=3.11.4
  - setuptools=68.0.0
  - wheel=0.40.0
  - bibtexparser=1.4.0
  - pip:
      - biblib==0.1.3
      - marshmallow-dataclass==8.5.14
      - minio==7.1.15
      - pika==1.3.2
      - pytest==7.4.0
      - pytest-mock==3.11.1
      - semver==3.0.1

